alias ..='cd ..'
alias c='clear'
alias change-terminal='sudo update-alternatives --config x-terminal-emulator'
alias commit='git commit -m'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gc='git checkout'
alias grep='grep --color=auto'
alias install='sudo apt install'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias log='git log --oneline'
alias ls='ls --color=auto'
alias status='git status'
alias update='sudo apt update && sudo apt upgrade'
alias psql="psql -h localhost"
